name: Create aircrafts data

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 3,15 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "adb"
  adb:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      - name: Run install
        run: |
            cd $GITHUB_WORKSPACE ;
            sudo apt-get update ;
            sudo apt-get install coreutils ;
            sudo apt-get install libjson-xs-perl libio-socket-ssl-perl ;
            wget https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz ;
            tar xzf Python-2.7.18.tgz ;
            cd Python-2.7.18 ;
            ./configure --prefix=/usr/local ;
            make ;
            sudo make install ;

      - name: Run script
        run: |
            cd $GITHUB_WORKSPACE/software/utils ;
            # rm -f cdb/ogn.cdb cdb/ogn.md5 ;
            # rm -f cdb/fln.cdb cdb/fln.md5 ;
            mkdir -p db cdb ;
            wget -P db https://github.com/lyusupov/SoftRF/raw/refs/heads/master/software/data/Aircrafts/icao.db ;
            sh ogn.sh ;
            mv ogn.db db/ ;
            mv ogn.cdb cdb/ ;
            # md5sum db/ogn.db > db/ogn.md5 ;
            # md5sum cdb/ogn.cdb > cdb/ogn.md5 ;
            # chmod a-w cdb/ogn.cdb cdb/ogn.md5 ;
            sh fln.sh ;
            mv fln.db db/ ;
            mv fln.cdb cdb/ ;
            # md5sum db/fln.db > db/fln.md5 ;
            # md5sum cdb/fln.cdb > cdb/fln.md5 ;
            # chmod a-w cdb/fln.cdb cdb/fln.md5 ;
            date >  README.txt ;
            echo >> README.txt ;
            echo 'Use data files in "db"  folder with SkyView EZ' >> README.txt ;
            echo 'Use data files in "cdb" folder with SkyView Pico, Badge or Prime Mk3 Editions' >> README.txt ;

      - uses: actions/upload-artifact@v4
        with:
          name: Data
          path: |
            software/utils/db/
            software/utils/cdb/
            software/utils/README.txt
          if-no-files-found: warn
          retention-days: 7

